import Fluent
import Foundation
import Vapor

/// Per-user evaluation of a feed_item: relevance, tldr, why_this, lane,
/// generated by an LLM rerank against THIS user's blurb (not the global
/// owner blurb in Data/interests.md). Drives personalized card content
/// in the feed.
///
/// Embeddings + dedup live on the global `item_scores` row — those are
/// user-agnostic and shared. This table only holds the human-readable
/// evaluation that varies by user.
///
/// Writes go through raw SQL in ScoreCommand. The Model is for read access.
final class UserItemScore: Model, @unchecked Sendable {
    static let schema = "user_item_scores"

    @ID(key: .id) var id: UUID?
    @Parent(key: "user_id") var user: User
    @Parent(key: "item_id") var item: FeedItem
    @OptionalField(key: "relevance_score") var relevanceScore: Int?
    @OptionalField(key: "tldr") var tldr: String?
    @OptionalField(key: "why_this") var whyThis: String?
    @OptionalField(key: "lane") var lane: String?
    @OptionalField(key: "scored_at") var scoredAt: Date?

    init() {}
}
